[2025-04-05 20:29:15,573] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Hello_ETL.load_transform_export 2025-04-05T14:58:13.861725+00:00 [queued]>
[2025-04-05 20:29:15,594] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Hello_ETL.load_transform_export 2025-04-05T14:58:13.861725+00:00 [queued]>
[2025-04-05 20:29:15,594] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2025-04-05 20:29:15,594] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2025-04-05 20:29:15,594] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2025-04-05 20:29:15,600] {taskinstance.py:901} INFO - Executing <Task(BashOperator): load_transform_export> on 2025-04-05T14:58:13.861725+00:00
[2025-04-05 20:29:15,602] {standard_task_runner.py:54} INFO - Started process 60211 to run task
[2025-04-05 20:29:15,630] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Hello_ETL', 'load_transform_export', '2025-04-05T14:58:13.861725+00:00', '--job_id', '24', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/simplest_dag.py', '--cfg_path', '/tmp/tmpt0tk7yuw']
[2025-04-05 20:29:15,630] {standard_task_runner.py:78} INFO - Job 24: Subtask load_transform_export
[2025-04-05 20:29:15,682] {logging_mixin.py:120} INFO - Running <TaskInstance: Hello_ETL.load_transform_export 2025-04-05T14:58:13.861725+00:00 [running]> on host ROGZephyrusG14GA401QHGA401QH2abf6ae9
[2025-04-05 20:29:15,720] {taskinstance.py:1150} ERROR - bash /home/parveensharma/Documents/PythonPractice/Airflow_ETL/wrapper.sh
Traceback (most recent call last):
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 965, in _run_raw_task
    self.render_templates(context=context)
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1424, in render_templates
    self.task.render_template_fields(context)
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 719, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 726, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 753, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /home/parveensharma/Documents/PythonPractice/Airflow_ETL/wrapper.sh
[2025-04-05 20:29:15,721] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=Hello_ETL, task_id=load_transform_export, execution_date=20250405T145813, start_date=20250405T145915, end_date=20250405T145915
[2025-04-05 20:29:20,591] {local_task_job.py:102} INFO - Task exited with return code 1
